In [31]:


# load sklearn mlp

# load saved model

# get 

from joblib import load
from imbalanced_data.code.util import utils


model = load("D:\\Programming\\PycharmProjects\\ba\\imbalanced_data\\data\\air_pressure\\03_trained\\2024_03_12_23_33_32\\MLP_None_fold-0_model.joblib") 
print(f"n_layers_: {model.n_layers_}")
print(f"n_outputs_: {model.n_outputs_}")
print(f"out_activation_: {model.out_activation_}")
print(f"n_features_in_: {model.n_features_in_}")
sum = 0
for (index, coef) in enumerate(model.coefs_):
    sum += len(coef)*len(coef[0])
    print(f"coefs_[{index}] | length: {len(coef)} | width: {len(coef[0])}")
print(sum)

features = utils.unpickle("D:\\Programming\\PycharmProjects\\ba\\imbalanced_data\\data\\air_pressure\\01_preprocessed\\2024_03_08_18_57_50\\fold-0_test_features.npy", is_numpy=True)
labels = utils.unpickle("D:\\Programming\\PycharmProjects\\ba\\imbalanced_data\\data\\air_pressure\\01_preprocessed\\2024_03_08_18_57_50\\fold-0_test_labels.npy", is_numpy=True)
pred = model.predict(features)
print(pred[:10])

n_layers_: 3
n_outputs_: 1
out_activation_: logistic
n_features_in_: 161
coefs_[0] | length: 161 | width: 100
coefs_[1] | length: 100 | width: 1
16200
[0 0 0 0 0 0 0 0 0 0]


In [ ]:
16301 - 100 -1

161*100 = 16100
100*1 = 100



In [6]:
import torch
from torch import nn

input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5).softmax(dim=1)
# output = nn.CrossEntropyLoss(input, target)
print(input)  
print(target)
# print(output)

tensor([[-0.8126,  1.1367, -0.0326,  0.0743, -0.6228],
        [ 1.1183, -1.4793,  0.2225,  0.7601,  0.9159],
        [-0.9408,  0.4992,  0.0550,  1.3709,  0.1245]], requires_grad=True)
tensor([[0.1267, 0.4241, 0.0841, 0.1542, 0.2110],
        [0.4966, 0.1397, 0.1095, 0.1644, 0.0898],
        [0.1357, 0.3296, 0.2232, 0.2178, 0.0937]])


In [1]:
from torch import Tensor

list = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]

print(Tensor(list).unsqueeze(1).squeeze())

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1.])


In [4]:
import numpy as np

list = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
labels = np.array(list).reshape((-1, 1))
print(labels)
print(labels.shape[1])

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]]
1


In [42]:
import numpy as np

arr = np.array([-0.6690, -0.6706, -0.6602, -0.6862, -0.6564, -0.6509, -0.6546, -0.6772,
        -0.6583, -0.6767])
print((arr < -0.67).astype(int))

[0 1 0 1 0 0 0 1 0 1]


In [9]:
from imbalanced_data.code.util import utils
import numpy as np

sampled_labels = utils.unpickle("D:\\Programming\\PycharmProjects\\ba\\imbalanced_data\\data\\air_pressure\\02_sampled\\2024_03_10_17_33_25\\None_fold-0_train_labels.npy", is_numpy=True)
labels = sampled_labels[:10]
print(labels)


[0 0 0 0 0 0 0 0 1 0]


In [22]:

print(np.column_stack((labels, 1-labels)))

[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]


In [3]:
import torch
x = torch.Tensor([[0.5270, 0.5147],
[0.5262, 0.5194],
[0.5252, 0.5216],
[0.5221, 0.5240],
[0.5227, 0.5258],
[0.5350, 0.5207],
[0.5253, 0.5254],
[0.5152, 0.5201],
[0.5230, 0.5224],
[0.5283, 0.5178]])

print(torch.Tensor([[1, 2],[3, 4],[5, 6],[7, 8]]).transpose(0,1))
# torch.Tensor([[1, 3, 5 ,7],[2, 4, 6, 8]])

print(torch.Tensor([0, 1, 1,1,0,0,1,1,0,1]).reshape(-1, 1))

tensor([[1., 3., 5., 7.],
        [2., 4., 6., 8.]])
tensor([[0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.]])
